//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleDocumentStoreWebApi.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
   
    public partial class Doc
    {
        public Doc()
        {
            this.DocIndexValues = new HashSet<DocIndexValue>();
        }
    
        public int Id { get; set; }
        public Nullable<System.Guid> SystemGuid { get; set; }
        public string SystemDocId { get; set; }
        public Nullable<int> DocTypeId { get; set; }
        public byte[] DocBinary { get; set; }
        public string FilePath { get; set; }
        public string FileType { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual DocType DocType { get; set; }
        public virtual ICollection<DocIndexValue> DocIndexValues { get; set; }
    }
}
