//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleDocumentStoreWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocIndexValue
    {
        public int Id { get; set; }
        public Nullable<int> DocIndexId { get; set; }
        public string DocIndexValueField { get; set; }
        public Nullable<int> DocId { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> SystemGuid { get; set; }
    
        public virtual Doc Doc { get; set; }
        public virtual DocIndex DocIndex { get; set; }
    }
}
