//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleDocumentStoreWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocTypeConfiguration
    {
        public int Id { get; set; }
        public Nullable<int> DocTypeId { get; set; }
        public Nullable<int> DocIndexId { get; set; }
        public bool IsRequired { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual DocIndex DocIndex { get; set; }
        public virtual DocType DocType { get; set; }
    }
}
